services:
  # Datenbank
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  # Microservice 1
  microservice1:
    build:
      context: ./microservice1
    ports:
      - "8081:8081"
    environment:
      - LOGSTASH_HOST=logstash
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
      - jaeger-all-in-one
      - logstash

  # Microservice 2
  microservice2:
    build:
      context: ./microservice2
    ports:
      - "8082:8082"
    environment:
      - LOGSTASH_HOST=logstash
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
      - jaeger-all-in-one
      - logstash

  # Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - microservice1

  # Monitoring-Stack
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - jaeger-all-in-one
      - elasticsearch

  # Jaeger All-in-One-Dienst (In-Memory-Speicher)
  jaeger-all-in-one:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.10.0
    container_name: jaeger-all-in-one
    ports:
      - "16686:16686" # Web UI
      - "4317:4317" # OTLP gRPC - Standard für OpenTelemetry
      - "14250:14250" # Klassischer gRPC Collector Port
      - "6831:6831/udp" # Agent Thrift UDP

  # ELK Stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    container_name: logstash
    ports:
      - "5001:5000"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  db-data: