server.port=8081
spring.application.name=microservice1
next.service.url=http://microservice2:8082
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.otlp.tracing.endpoint=http://jaeger-all-in-one:4318/v1/traces
management.tracing.sampling.probability=1.0