server.port=8082
spring.application.name=microservice2
next.service.url=
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.otlp.tracing.endpoint=http://jaeger-all-in-one:4318/v1/traces
management.tracing.sampling.probability=1.0