server.port=8082
spring.application.name=microservice2
next.service.url=
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.tracing.exporter.otlp.endpoint=http://jaeger-all-in-one:4317
management.tracing.sampling.probability=1.0